### PR TITLE
Xcode 13 Beta 3+ fix

### PR DESCRIPTION
**Pull request by apps4everyone**
https://github.com/danielsaidi/Sheeeeeeeeet/issues/148

### CODE REVIEW

**Comment by apps4everyone** [comment]
just found this:
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11

but there is also a bug ticket:
https://bugs.swift.org/browse/SR-14944

but maybe we can merge this PR because I think it doesn't hurt and also e.g. firebase SDK is doing this:
https://github.com/firebase/firebase-ios-sdk/pull/8405/files#diff-6a7bed552bbfb829f13887fa2c52795713e836e9feab53d4c603e338f1084fc1R21

**Comment by danielsaidi** [comment]
Hmmmm, I rebased a bunch of readme commits together when creating the new version, and now your PR is broken :( 

Sorry about that! Could you rebase and update?

**Comment by apps4everyone** [comment]
> Hmmmm, I rebased a bunch of readme commits together when creating the new version, and now your PR is broken :(
> 
> Sorry about that! Could you rebase and update?

would it be possible to set Quick back to min 3.0.0? Otherwise there is again a incompatibility with other packages

**Comment by danielsaidi** [comment]
Yes, I’ll try from 3

**Comment by danielsaidi** [comment]
I have pushed a patch that uses 3.0.

Regarding the `@available` annotation, I'd love to find a better way, since this makes many things unavailable, where we instead should just adjust the call-site.

For instance:

```
static var defaultPresenter: ActionSheetPresenter {
    let traits = UIApplication.shared.keyWindow?.traitCollection
    return defaultPresenter(forTraits: traits)
}
```

Here, I'd prefer an `applicationTraits` that returns `UIApplication.shared.keyWindow?.traitCollection` and is annotated with the `@available` annotation. The presenter could then use `applicationTraits` IF it runs in an app, otherwise use e.g. the main screen's traits.

We could then inject the window into the `ActionSheetStandardPresenter` from this file as well, to remove the dependency it has to the shared application. 

This would leave the rest of the library unchanged.

**Comment by danielsaidi** [comment]
Hi @apps4everyone - just wanted to give you an update, that I fixed this in another way that involved removing the usage of UIApplication.shared altogether. The annotation is nice, but I think removing the usage is better.

Thank you for helping out with this!

**Comment by apps4everyone** [comment]
thx, will test. maybe you can mark as latest release?
https://github.com/danielsaidi/Sheeeeeeeeet/releases has still 3.1.6

**Pull request closed without merging**
