### PR TITLE
itemTextAlignment proxy added

### PR DESCRIPTION
**Pull request by mohammadghk**
`itemTextAlignment` added to item proxies for changing item's `textLabel` and `detailedTextLabel` , `textAlignment` to make Sheeeeeeeeet❤️   more RTL language friendly :)

### CODE REVIEW

**Comment by danielsaidi** [comment]
Amazing, thank you!

**Comment by danielsaidi** [comment]
@mohammadghk Hi again! I'm trying to get this to work, but setting `textLabel?.textAlignment` does nothing for me.

**Comment by mohammadghk** [comment]
Yes Actually because `textLabel?.textAlignment` is being override in `refresh()` .
Well I wanted it to work for the whole app so I changed `refresh()`  in `ActionSheetItemCell`. Try to use it in AppDelegate like this:
`let item = ActionSheetItemCell.appearance()`
`item.itemTextAlignment = .right`

I guess I need to make it applicable for each item instead of setting in appearance proxy so should I try to change `ActionSheetItem` ?
The result that I'm currently using is like this: 
Screen Shot 2019-10-12 at 10 19 58 AM

**Comment by danielsaidi** [comment]
Ah, ok I see! I have removed the explicit text alignment logic from the cells and moved it all to the appearance class, so it's easily overridable now. You can test it in `master`.

One thing I noticed, however, is that the rtl logic doesn't apply when the cell uses `.subtitle` as cell style. See this image:

image

**Pull request merged**
